local M = {}

local timer = vim.uv.new_timer()
local config_path = vim.fn.expand("~/.config/ghostty/nvchad-theme")
local tmux_config_path = vim.fn.expand("~/.tmux/nvchad-theme.conf")
M.state_path = vim.fn.expand("~/.cache/nvchad_current_theme")

function M.sync()
  timer:stop()
  timer:start(200, 0, vim.schedule_wrap(function()
    local ok30, base30 = pcall(function()
      return require("base46").get_theme_tb("base_30")
    end)
    local ok16, base16 = pcall(function()
      return require("base46").get_theme_tb("base_16")
    end)

    if not ok30 or not ok16 then
      return
    end

    local lines = {
      "# Auto-generated by NvChad ghostty_sync — do not edit",
      "background = " .. base16.base00,
      "foreground = " .. base16.base05,
      "",
      "palette = 0=" .. base16.base01,
      "palette = 1=" .. base30.red,
      "palette = 2=" .. base30.green,
      "palette = 3=" .. base30.yellow,
      "palette = 4=" .. base30.blue,
      "palette = 5=" .. base30.dark_purple,
      "palette = 6=" .. base30.teal,
      "palette = 7=" .. base16.base05,
      "",
      "palette = 8=" .. base30.light_grey,
      "palette = 9=" .. base30.baby_pink,
      "palette = 10=" .. base30.vibrant_green,
      "palette = 11=" .. base30.sun,
      "palette = 12=" .. base30.nord_blue,
      "palette = 13=" .. base30.purple,
      "palette = 14=" .. base30.cyan,
      "palette = 15=" .. base16.base07,
      "",
      "cursor-color = " .. base16.base05,
      "cursor-text = " .. base16.base00,
      "selection-background = " .. base30.one_bg2,
      "selection-foreground = " .. base16.base05,
      "",
    }

    local f = io.open(config_path, "w")
    if f then
      f:write(table.concat(lines, "\n"))
      f:close()
      os.execute("killall -SIGUSR2 ghostty 2>/dev/null")
    end

    -- Sync tmux colors
    local tmux_lines = {
      "# Auto-generated by NvChad ghostty_sync — do not edit",
      "",
      "# Status bar",
      'set -g status-style "bg=' .. base16.base01 .. ',fg=' .. base16.base05 .. '"',
      "",
      "# Active window tab",
      'set -g window-status-current-style "bg=' .. base30.blue .. ',fg=' .. base16.base00 .. ',bold"',
      'set -g window-status-current-format " #I:#W "',
      "",
      "# Inactive window tabs",
      'set -g window-status-style "bg=' .. base16.base01 .. ',fg=' .. base30.light_grey .. '"',
      'set -g window-status-format " #I:#W "',
      "",
      "# Pane borders",
      'set -g pane-border-style "fg=' .. base30.one_bg2 .. '"',
      'set -g pane-active-border-style "fg=' .. base30.blue .. '"',
      "",
      "# Messages",
      'set -g message-style "bg=' .. base30.one_bg .. ',fg=' .. base16.base05 .. '"',
      'set -g message-command-style "bg=' .. base30.one_bg .. ',fg=' .. base16.base05 .. '"',
      "",
      "# Mode (copy mode highlight)",
      'set -g mode-style "bg=' .. base30.one_bg2 .. ',fg=' .. base16.base05 .. '"',
      "",
    }

    local tf = io.open(tmux_config_path, "w")
    if tf then
      tf:write(table.concat(tmux_lines, "\n"))
      tf:close()
      os.execute("tmux source-file ~/.tmux.conf 2>/dev/null")
    end

    -- Write theme name so other Neovim instances can pick it up
    local theme = require("nvconfig").base46.theme
    local sf = io.open(M.state_path, "w")
    if sf then
      sf:write(theme)
      sf:close()
    end
  end))
end

return M
